config/routes.rb
Rails.application.routes.draw do
  root 'pages#invite'

  get '/home', to: 'pages#home'

  get '/about', to: 'pages#about'

  post '/guest_access', to: 'guest_sessions#create'

  delete '/guest_bye', to: 'guest_sessions#destroy'

  get '/party_rock', to: 'parties#index'

  post '/party_upon', to: 'parties#create'

  post '/party_code', to: 'parties#party_code'

  post '/a_thing', to: 'hosts#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :hosts do
  	resources :parties
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/party.rb
class Party < ApplicationRecord
attr_accessor :party_code_token
  belongs_to :host
  validates :tag,  presence: true
  validates :address,  presence: true
  validates :date,  presence: true
  validates :start_time,  presence: true
  validates :end_time,  presence: true
  validates :is_public,  presence: true
  validates :rating,  presence: true
  
  #returns a random token for the party_code
  def Party.new_token
  	SecureRandom.urlsafe_base64
  end

  def create_code
  	self.party_code_token = Party.new_token
    update_attribute(:party_code_digest, Party.digest(party_code_token))
  end

  def authenticated?(party_code_token)
  	return false if party_code_digest.nil?
    BCrypt::Password.new(party_code_digest).is_password?(party_code_token)
  end


end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
	before_action :end_guest_session, only: [:index]
	#display all parties
	def index
		@parties = Party.all
	end

	def new
	end

	def create
		Stripe.api_key = "sk_test_4WpGBozjMj2Fp8hJSNR2E63N"
		token = params[:stripeToken]

		@charge = Stripe::Charge.create({
    			amount: 299,
    			currency: 'usd',
    			description: 'Host ',
    			source: token,
		})

		if !@charge.nil?
			@party = Party.new(party_params)
			@party.rating = 0
			@party.create_code #calls the party's create function to 
			if @party.save
			#generated party code page
			redirect_to @party
			else
				flash[:error] = "Unable to create your event. Please try again."
			end
		end
	end

	def show
		@party = Party.find(params[:id])
	end

	def edit
		@party = Party.find(params[:id])
	end

	def update
		@party = Party.find(params[:id])
		if @party.update_attributes(party_params)
			flash[:success] = "Profile Updated"
			redirect_to @party
		else 
			flash[:error] = "Unable to update your account"
		end
	end

	def party_code
		party = Party.find_by(party_code: params[:party_code])
		if !party.nil? #party exists
			redirect_to party
		else
			flash[:error] = "Unable to find your event. It might not exist or you entered the wrong code."
		end
	end

	def destroy
		@party = Party.find(params[:id])
		@party.destroy
		#if logged in redirect_to hosts page if not redirect to 
	end

	private
		#get party parameters when a party is created
		def party_params
			params.require(:party).permit(:tag, :address, :date, :start_time,
                                   :end_time, :is_public, :rating)
		end


		#get the party code to allow access to the party page
		def party_code_params
			params.require(:party).permit(:party_code)
		end

		def end_guest_session
			if  end_access < Time.now
				redirect_to root_url
			end
		end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_party_code.html.erb
<div class="form-center">

<%= form_for(:parties, url: party_code_path ) do |f| %>
<label>
	<%= f.text_field :party_code,:required => true %>
	<div class="label-text" > Party Code </div>
</label>
<%= f.submit "Find", :id =>"party-code-submit" %>
<% end %>
<h4 class="form-header" id="logIn-slide"> BACK TO LOGIN</h4>
</div>

app/views/parties/_party_upon.html.erb
<div class="form-center" id="one-time-host-form">
<h4 class="form-header" > CREATE AN EVENT </h4>

<%= form_for(:parties, url: party_upon_path, :id => 'host-payment-form') do |f| %>


<label>
<%= f.text_field :tag,:required => true %>
<div class="label-text" > Tag </div>
</label>

<label>
<%= f.text_field :address, :id => "autocomplete", :onFocus => "geolocate()" , :placeholder => " ", :required => true %>
<div class="label-text" > Street Address </div>
</label>


<%= f.hidden_field :longitude %>
<%= f.hidden_field :latitude %>
<%= f.hidden_field :rating, :value => 0 %>
<%= f.hidden_field :start_time %>
<%= f.hidden_field :end_time %>


<label>
<%= f.date_field :date,:required => true %>
<div class="label-text" > Date </div>
</label>


<label>
<input type="time" required />
<div class="label-text" > start time </div>
</label>


<label>
<input type="time" required />
<div class="label-text" > end time </div>
</label>

<label>
<%= f.check_box :is_public,:required => true %>
<div class="label-text" > is public </div>
</label>


<h4 class="form-header" id="one-time-host-payment-header"> SECURE YOUR EVENT </h4>
<div class="host-arrows"></div>

</div>

<div class="form-center" id="one-time-host-payment">

	
	  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="host-card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="host-card-errors" role="alert"></div>
  </div>



<script>
	var autocomplete;
    var stripe = Stripe('pk_test_4WpGfqeTASO8DL3ZKyQNcM2U');
  var elements = stripe.elements();
  var style = {
    base: {
    // Add your base input styles here. For example:
      fontSize: '12px',
      color: "rgba( 0, 188, 212, 1)", 
      fontFamily: "'Monda', sans-serif",
      letterSpacing: '3px',    
  }
};

// Create an instance of the card Element.
  var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
  card.mount('#host-card-element');


  card.addEventListener('change', function(event) {
  var displayError = document.getElementById('host-card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

  // Create a token or display an error when the form is submitted.
var form = document.getElementById('host-payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the customer that there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});



function codeAddress() {
    var address = document.getElementById('parties_address').value;
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == 'OK') {
      	document.getElementById('parties_latitude').value = results[0].geometry.location[0];
      	document.getElementById('parties_longitude').value = results[0].geometry.location[1];
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }

  function geolocate() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var geolocation = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };
      var circle = new google.maps.Circle({
        center: geolocation,
        radius: position.coords.accuracy
      });
      autocomplete.setBounds(circle.getBounds());
    });
  }
}

  </script>
	
	<%= f.submit "Party On", :id => "party-submit", :onclick =>"codeAddress()" %>

	<h4 class="form-header" id="one-time-host-back"> BACK </h4>
</div>



<% end %>

app/views/parties/index.html.erb
<% provide(:title, "Party Rock") %>
<p> Displays all parties </p>


<h4> Your Session Expires at <%= time_split %> </h4>

<h4> Time Left </h4>
<h4 id="time_left">0</h4>

    <div id="allParties"></div>


    <script>
      function allMap() {
      	<% @parties.each do |party| %>
        var uluru = {lat: @party.latitude, lng: @party.longitude };
        var map = new google.maps.Map(document.getElementById('allParties'), {
          zoom: 13,
          center: uluru,
          disableDefaultUI: true,
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
       <% end %>

    </script>


    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDryw1evdmCtZ73TXe2TqM1jTWhloVbBtU&libraries=places&callback=allParties">
    </script>

app/views/parties/show.html.erb
<% provide(:title, "Party Page") %>
<h4 class="form-header"> <%= @party.party_code %></h4>
    <div id="partyPage"></div>

    <script>
      function showMap() {
        var uluru = {lat: @party.latitude, lng: @party.longitude };
        var map = new google.maps.Map(document.getElementById('partyPage'), {
          zoom: 13,
          center: uluru,
          disableDefaultUI: true,
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });

    </script>


    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDryw1evdmCtZ73TXe2TqM1jTWhloVbBtU&libraries=places&callback=showMap">
    </script>
 