config/routes.rb
Rails.application.routes.draw do
  root 'pages#invite'

  get '/home', to: 'pages#home'

  get '/about', to: 'pages#about'

  post '/guest_access', to: 'guest_sessions#create'

  delete '/guest_bye', to: 'guest_sessions#destroy'

  get '/party_rock', to: 'parties#index'

  post '/party_upon', to: 'parties#create'

  post '/party_code', to: 'parties#party_code'

  post '/a_thing', to: 'hosts#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :hosts do
  	resources :parties
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/host.rb
class Host < ApplicationRecord
  has_many :parties dependent: :destroy
  attr_accessor :remember_token
	before_save { email.downcase! }
	validates :username,  presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    def Host.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end


    def Host.new_token
      SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = Host.new_token
      update_attribute(:remember_digest, Host.digest(remember_token))
  end

    # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update, :destroy]
	before_action :correct_user,   only: [:edit, :update]
	before_action :admin_user,     only: :destroy

	def new
		@host = Host.new
	end

	def create
		@host = Host.new(host_params)
		@host.is_admin = true
		if @host.save
			flash[:success] = "We like you...ALOT"
			log_in @host
			redirect_to @host
		else
			redirect_to home_path
			flash[:error] = "Unable to create your account. Please try again."
		end
	end

	def show
		@host = Host.find(params[:id])
		@myEvents = Party.find_by(host_id: @host.id)
	end

	def edit
		@host = Host.find(params[:id])
	end

	def update
		@host = Host.find(params[:id])
		if @host.update_attributes(host_params)
			flash[:success] = "Profile Updated"
			redirect_to @host
		else 
			flash[:error] = "Unable to update your account"
		end
	end

	def destroy
		@host = Host.find(params[:id])
		@host.destroy
		redirect_to root_url
	end

	private
		def host_params
			params.require(:host).permit(:username, :email, :password, :password_confirmation)
		end

		def logged_in_user
      		unless logged_in?
       		 	flash[:danger] = "Please log in."
        		redirect_to login_url
      		end
    	end

    	def correct_user
     		 @host = Host.find(params[:id])
     		 redirect_to(root_url) unless current_host?(@host)
   		end

   		def admin_user
      		redirect_to(root_url) unless current_host.admin?
    	end
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_edit.html.erb
<div class="form-center" id="edit-form">
<h4 class="form-header"> TALKING ABOUT UPDATES </h4>
<%= form_for(@host) do |f| %>
<label>
<%= f.text_field :username,:required => true %>
<div class="label-text" > Username </div>
</label>

<label>
<%= f.email_field :email,:required => true %> 
<div class="label-text" > Email </div>
</label>

<label>
<%= f.password_field :password, :required => true %>
<div class="label-text" > Password </div>
</label>

<label>
<%= f.password_field :password_confirmation, :required => true %>
<div class="label-text" > Password Confirmation </div>
</label>

<%= f.submit "UPDATE", :id => "update-bttn" %>
<% end %>
</div>

app/views/hosts/_host_acct.html.erb
<div class="form-center">
<h4 class="form-header"> LET'S MAKE THIS A THING </h4>
<%= form_for :host, url: a_thing_path do |f| %>
<label>
<%= f.text_field :username,:required => true %>
<div class="label-text" > Username </div>
</label>

<label>
<%= f.email_field :email,:required => true %> 
<div class="label-text" > Email </div>
</label>

<label>
<%= f.password_field :password, :required => true %>
<div class="label-text" > Password </div>
</label>

<label>
<%= f.password_field :password_confirmation, :required => true %>
<div class="label-text" > Password Confirmation </div>
</label>

<%= f.submit "You + us = WE...like OFFICIAL" %>
<% end %>
</div>

app/views/hosts/_my_event.html.erb
  <div id="hostMap"></div>

    <script>
      function initMap() {
        var uluru = {lat: -22.915, lng: -43.197};
        var map = new google.maps.Map(document.getElementById('hostMap'), {
          zoom: 13,
          center: uluru,
          disableDefaultUI: true,
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
 
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDryw1evdmCtZ73TXe2TqM1jTWhloVbBtU&callback=initMap">
    </script>

<p> Search Event </p>

app/views/hosts/show.html.erb
<% provide(:title, "Dashboard") %>
<div id="host-dash">
		<h4 id="host-greeting"> Hello, <%= @host.username %></h4>
	  <div id="mapDash"></div>

    <script>
      function initMap() {
        var uluru = {lat: -22.915, lng: -43.197};
        var map = new google.maps.Map(document.getElementById('mapDash'), {
          zoom: 13,
          center: uluru,
          disableDefaultUI: true,
          gestureHandling: 'none', 
          zoomControl: false,
          styles: [
  {
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#f5f5f5"
      }
    ]
  },
  {
    "elementType": "labels.icon",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#616161"
      }
    ]
  },
  {
    "elementType": "labels.text.stroke",
    "stylers": [
      {
        "color": "#f5f5f5"
      }
    ]
  },
  {
    "featureType": "administrative.land_parcel",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#bdbdbd"
      }
    ]
  },
  {
    "featureType": "administrative.neighborhood",
    "elementType": "labels.icon",
    "stylers": [
      {
        "color": "#ffeb3b"
      }
    ]
  },
  {
    "featureType": "administrative.province",
    "elementType": "labels.icon",
    "stylers": [
      {
        "color": "#de5fff"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#eeeeee"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#757575"
      }
    ]
  },
  {
    "featureType": "poi.attraction",
    "elementType": "labels.icon",
    "stylers": [
      {
        "color": "#79e56a"
      }
    ]
  },
  {
    "featureType": "poi.business",
    "elementType": "labels.icon",
    "stylers": [
      {
        "color": "#67bfe5"
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#e5e5e5"
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#9e9e9e"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#ffffff"
      }
    ]
  },
  {
    "featureType": "road.arterial",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#757575"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#dadada"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#616161"
      }
    ]
  },
  {
    "featureType": "road.local",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#9e9e9e"
      }
    ]
  },
  {
    "featureType": "transit.line",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#e5e5e5"
      }
    ]
  },
  {
    "featureType": "transit.station",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#eeeeee"
      }
    ]
  },
  {
    "featureType": "transit.station.airport",
    "elementType": "labels.icon",
    "stylers": [
      {
        "color": "#9ea9e5"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#c9c9c9"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#9e9e9e"
      }
    ]
  }
]
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
 
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDryw1evdmCtZ73TXe2TqM1jTWhloVbBtU&callback=initMap">
    </script>
	

	<div id="host-opts-dash">
		<p class="opt-tags" id="host-event"> Create Event </p>
		<p class="opt-tags" id="host-myEvents"> myEvents </p>
		<p class="opt-tags" id="host-acct-settings"> Account Settings </p>
		<p class="opt-tags" id="host-logout"> <%= link_to "Log out", logout_path, method: :delete, :class => "dash-opts opt-tags" %></p>
	</div>

	<div class="host-viewer">
		<div class="host-dash" id="host-event-opts">
			<%= render 'parties/party_upon' %>
		</div>

		<div class="host-dash" id="host-myEvent-opts">
			<%= render 'hosts/my_event' %>
		</div>

		<div class="host-dash" id="host-acct-opts">
			<%= render 'edit' %>
			<p id="delete-acct"> <%= link_to "Delete Account", @host, method: :delete,
                                  data: { confirm: "You sure?" } %>
 			
 			</p>
		</div>
	</div>

</div>