config/routes.rb
Rails.application.routes.draw do
  root 'pages#invite'

  get '/home', to: 'pages#home'

  get '/about', to: 'pages#about'

  post '/guest_access', to: 'guest_sessions#create'

  delete '/guest_bye', to: 'guest_sessions#destroy'

  get '/party_rock', to: 'parties#index'

  post '/party_upon', to: 'parties#create'

  post '/party_code', to: 'parties#party_code'

  post '/a_thing', to: 'hosts#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :hosts do
  	resources :parties
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<% provide(:title, "About") %>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
    <div id="mapHome"></div>

    <script>
    var autocomplete;
      function initMap() {
        var uluru = {lat: -22.915, lng: -43.197};
        var map = new google.maps.Map(document.getElementById('mapHome'), {
          zoom: 13,
          center: uluru,
          disableDefaultUI: true,
          gestureHandling: 'none', 
          zoomControl: false
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });

      autocomplete = new google.maps.places.Autocomplete(
      /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
      {types: ['geocode']});
      }
    </script>
 

<div class="invite-map">
	<p class="opt-tags" id="rate"> Rate </p>
	<p class="opt-tags" id="guest"> Guest </p>
	<p class="opt-tags" id="acct"> Host </p>
	<p class="opt-tags" id="onetime"> Host </p>
	<p class="opt-tags" id="logInCode"> LogIn/PartyCode </p>
</div>

<div class="options" id="rate-opts">
   <button class="close-bttn">X </button>
   <h4 class="form-header"> ALLOW US TO LOCATE YOUR PARTY </h4>
   <p class="content-paragraphs"> You may only rate Events which you are currently attending...otherwise we believe in our most humble opinion that that's just not honest. May we verify your location? </p>
   <p id="location_determined" class="content-paragraphs"></p> 


   <button onclick ="LocateGuest()"class="locator"> Locate Me </button>
    <script>
    var x = document.getElementById("location_determined")
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.

      function LocateGuest() {
 
        // Try HTML5 geolocation.
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(getLongLat);
        }else{
          x.innerHTML = "Geolocation is not supported by this browser."
        }
      }
      function getLongLat(pos){
        x.innerHTML = "You were matched to the following events."
      }

    </script>

</div>

<div class="options" id="guest-opts">
  <button class="close-bttn">X </button>
	<%= render 'guest_sessions/login_guest' %>
</div>

<div class="options" id="acct-host">
   <button class="close-bttn">X </button>
  <%= render 'hosts/host_acct' %>
</div>

<div class="options" id="logIn">
   <button class="close-bttn">X </button>
  <%= render 'sessions/login_hosts' %>
  <h4 class="form-header" id="party-code"> HOSTS WITHOUT ACCOUNTS </h4>
  <div class="form-center" id="party-code-edit">
    <%= render 'parties/party_code' %>
 </div>
</div>

<div class="options" id="host-opts">
   <button class="close-bttn">X </button>

   <%= render 'parties/party_upon' %>
</div>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDryw1evdmCtZ73TXe2TqM1jTWhloVbBtU&libraries=places&callback=initMap">
    </script>

app/views/pages/invite.html.erb
<% provide(:title, "Welcome") %>
    <div id="map"></div>

    <script>
      function initMap() {
        var uluru = {lat: -22.915, lng: -43.197};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 13,
          center: uluru,
          disableDefaultUI: true,
          gestureHandling: 'none', 
          zoomControl: false
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
 
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDryw1evdmCtZ73TXe2TqM1jTWhloVbBtU&callback=initMap">
    </script>

<div id="invite-content">
<p id="invite"> 
</p>
</div>

<div class="invite-map">
</div>

<div class="bubbles" id="one">
</div>
<div class="bubbles" id="second">
</div>
<div class="bubbles" id="third">
</div>


<div class="location-marker-container">
</div>
<div class="location-marker-container-second">
</div>
<div class="location-marker">
	<span class="tooltiptext"><%= link_to "Yes", home_path %><span>
</div>